services:
  - type: web
    name: churn-prediction-api
    runtime: docker
    rootDir: MLOps/churn-model-serving
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
